import type { Task } from '../types/agent';

/**
 * Extended task interface for structured planning.
 */
export interface StructuredTask extends Task {
  tool: string;
  dependencies: string[];
  ui_component?: string;
  ui_props?: Record<string, unknown>;
}
/**
 * Structured plan interface generated by the LLM.
 */
export interface StructuredPlan {
  id: string;
  goal: string;
  reasoning: string;
  tasks: StructuredTask[];
  createdAt: number;
  confidence?: number;
}

/**
 * Schema definition for the Plan (used for LLM guidance).
 */
export const PlanSchema = {
  type: 'object',
  properties: {
    id: { type: 'string' },
    goal: { type: 'string' },
    reasoning: { type: 'string' },
    confidence: { type: 'number', minimum: 0, maximum: 100 },
    tasks: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          id: { type: 'string' },
          description: { type: 'string' },
          tool: { type: 'string' },
          dependencies: {
            type: 'array',
            items: { type: 'string' }
          },
          ui_component: { type: 'string', description: 'Optional UI component type to render for this task result' },
          ui_props: { type: 'object', description: 'Optional props for the UI component' },
          metadata: { 
            type: 'object', 
            description: 'Critical: This object MUST contain all input parameters for the tool as specified in the "Input" section of the tool description (e.g., { "query": "..." } for search).'
          }
        },
        required: ['id', 'description', 'tool', 'dependencies', 'metadata']
      }
    }
  },
  required: ['id', 'goal', 'reasoning', 'tasks']
};
